### ISSUE TITLE
flutter+ios : "Undefined symbols for architecture xxx"

### ISSUE THREAD

**Issue by benoitskipr** [smartlook/smartlook-ios-sdk#17]
Hi, any idea why I get this (ios only) after adding smartlook 0.0.8 flutter lib ?

```
    Undefined symbols for architecture armv7:
      "_SLNavigationTypeExit", referenced from:
          -[SmartlookPlugin _internal_handleMethodCall:result:] in SmartlookPlugin.o
      "_SLNavigationTypeEnter", referenced from:
          -[SmartlookPlugin _internal_handleMethodCall:result:] in SmartlookPlugin.o
      "_OBJC_CLASS_$_Smartlook", referenced from:
          objc-class-ref in SmartlookPlugin.o
         (maybe you meant: _OBJC_CLASS_$_SmartlookPlugin)
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_Smartlook", referenced from:
          objc-class-ref in SmartlookPlugin.o
         (maybe you meant: _OBJC_CLASS_$_SmartlookPlugin)
      "_SLNavigationTypeExit", referenced from:
          -[SmartlookPlugin _internal_handleMethodCall:result:] in SmartlookPlugin.o
      "_SLNavigationTypeEnter", referenced from:
          -[SmartlookPlugin _internal_handleMethodCall:result:] in SmartlookPlugin.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

thanks

**Comment by benoitskipr** [comment]
debug builds fail differently 2 times out of 3, once with the above message.
release builds fail everytime

**Comment by benoitskipr** [comment]
Flutter 1.12.13+hotfix.8 • channel stable

**Comment by benoitskipr** [comment]
sometimes it's armv7, sometimes x86, I've added it to a new project, same issue. though your example from the package runs

**Comment by benoitskipr** [comment]
tried with 0.0.6, same issue

**Comment by pavel-kroh-smartlook** [comment]
Technically, this means the the Smartlook.framework (native SDK library) is somehow invisible to the XCode project. Why this happens, it is hard to say. Does this occur after some update (of Flutter or Smartlook) or did you just add Smartlook to your project? Did you try (silly question) completely remove and then add Smartlook to the project?

**Comment by benoitskipr** [comment]
yes, same result, also forgot to mention it fails on CI too (bitrise), so it's not my tooling.

I can't repro with brand new projects, but well with a really small one I just started this saturday
gotta find what's different between those

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-BE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.1)

**Comment by benoitskipr** [comment]
ok does NOT happen on Flutter+Obj-C projects, but with swift support it fails 2 builds out 3.

![Create_New_Flutter_Project](https://user-images.githubusercontent.com/52695909/77357465-81254e00-6d48-11ea-8f68-5c206c0aef26.png)

**Comment by benoitskipr** [comment]
Sometimes I can see errors about Swift 3 @objc something, but don't know how to fix
related to [this](https://stackoverflow.com/questions/44379348/the-use-of-swift-3-objc-inference-in-swift-4-mode-is-deprecated)

**Comment by benoitskipr** [comment]
(can also see lots of warnings about deprecation, and I see there's literally a `ios/Classes/Smartlook_Deprecated.h` in the lib, does not feel necessary there

**Comment by pavel-kroh-smartlook** [comment]
Hi, thanks a lot for providing additional details. 

Smartlook is pure Obj-C, there is thus no Swift @objc directive in its code.

As for the Smartlook_Deprected.h, these are deprecated methods of Smartlook SDK API kept there few more versions for the case somebody uses them. This header might be not necessary in Flutter plugin, but as we use the standard iOS SDK there, we put the header there, too. Are some of the deprecated methods warnings related to Smartlook?

My guess is that the issue is somewhere in the Flutter plugin-installing mechanism, that is for iOS based on Cocoapods which have their own chronic issues (namely with referenced Swift frameworks).

**Comment by benoitskipr** [comment]
so it's not an issue you have encountered in native ios ?
and you say I should enter it as a flutter compiler bug ?
thanks

**Comment by pavel-kroh-smartlook** [comment]
We test our SDK releases both with an Objc and a Swift app, and the host app for its development is a hybrid Objc/Swift app and we run to no issues with like this. What is puzzling is the instability - that there are cases when it works. This seems to point somewhere to the toolchain, does'n it? It may happen that some flag or tweak in Flutter plugin configuration may work this around, but the issue is definitively related to Flutter ecosystem.

**Comment by benoitskipr** [comment]
or some caching somewhere, thanks

**Comment by pavel-kroh-smartlook** [comment]
This thread might help: https://github.com/flutter/flutter/issues/41900

**Comment by pavel-kroh-smartlook** [comment]
@benoitskipr, does the issue persists or have you found some solution on your side?

**Comment by benoitskipr** [comment]
somehow I've disabled an other plugin of ours, and the builds are not blocked anymore, it still warns about smartlook archi in the logs, but the build works everytime ¯\_(ツ)_/¯
logs were very misleading, I blame apple
thanks for the support
