### ISSUE TITLE
UI API called on a background thread.

### ISSUE THREAD

**Issue by wangjiejacques** [smartlook/smartlook-ios-sdk#2]
Main Thread Checker: UI API called on a background thread: -[UIView drawViewHierarchyInRect:afterScreenUpdates:]
PID: 23576, TID: 3253980, Thread name: (none), Queue name: com.Smarlook.Smartlook.SnapshotQueue, QoS: 9
Backtrace:
4   XXXXXXXX                      0x0000000105910cb9 __43-[Smartlook takeScreenSnapshotWithVCClass:]_block_invoke + 369
5   libdispatch.dylib                   0x000000010ed872f7 _dispatch_call_block_and_release + 12
6   libdispatch.dylib                   0x000000010ed8833d _dispatch_client_callout + 8
7   libdispatch.dylib                   0x000000010ed90855 _dispatch_queue_serial_drain + 1162
8   libdispatch.dylib                   0x000000010ed911ea _dispatch_queue_invoke + 336
9   libdispatch.dylib                   0x000000010ed94102 _dispatch_root_queue_drain + 772
10  libdispatch.dylib                   0x000000010ed93da0 _dispatch_worker_thread3 + 132
11  libsystem_pthread.dylib             0x000000010f254169 _pthread_wqthread + 1387
12  libsystem_pthread.dylib             0x000000010f253be9 start_wqthread + 13

**Comment by wangjiejacques** [comment]
@jCharv Great, do you think you can fix this in a few days ?

**Comment by Nicholmon** [comment]
I have this issue too, and I would say it's pretty annoying, especially while debugging..

**Comment by MEnnabah** [comment]
Any updates on this?

**Comment by pavel-kroh-smartlook** [comment]
An update: 

we understand the warning is a bit unsettling, it is however harmless. 

The cause is that in order to keep the app UI flow seamless while recording the screenshots, some operations must be done in background thread. The method that is used is the best one for this purpose (fastest, most reliable) but its use causes this warning. 

So it is a trade-off.

Continually we evaluate the situation and test if there is a better solution.
