### ISSUE TITLE
RxSwift + RxCocoa

### ISSUE THREAD

**Issue by anisibor** [smartlook/smartlook-ios-sdk#20]
We are using Rx* libraries and after installing SmartlookSDK app started crashing. After setting up observing on UIView.frame and UIView.layoutSubviews I got error from Rx:

```
Collision between RxCocoa interception mechanism and KVO. To resolve this conflict please use this interception mechanism first.
Target: <UIView: 0x7fd4f0eca4f0; frame = (0 -6; 347 42); autoresize = RM+BM; layer = <CALayer: 0x7fd4eb530e50>>
  objectMessagesAlreadyBeingIntercepted : 2 elements
    - target : <UIView: 0x7fd4f0eca4f0; frame = (0 -6; 347 42); autoresize = RM+BM; layer = <CALayer: 0x7fd4eb530e50>>
    - interceptionMechanism : RxCocoa.RxCocoaInterceptionMechanism.kvo
```

Is there any way to use Smartlook and Rx* libs with native properties observings?

**Comment by pavel-kroh-smartlook** [comment]
Hi, we do swizzle the `UIView.layoutSubviews` in order to detect changes on the screen. It is specifically done in a way that does not normally conflict with others doing the same. Not sure what RxCocoa does there and why it complaints, but apparently they require some special treatment.

Did you try to change the order in which Smartlook and Rx* libraries are setup? Sometimes it may help.

**Comment by pavel-kroh-smartlook** [comment]
There seems to be no way making RxCocoa compatible with libraries that use the standard swizzling mechanism.
